### ISSUE TITLE
Undefined variable: view in MY_Controller.php

### ISSUE THREAD

**Issue by carlotrimarchi** [efendibooks/codeigniter-handbook-vol-1#3]
I'm getting this error:

Severity: Notice
Message: Undefined variable: view
Filename: core/MY_Controller.php
Line Number: 46

what am I doing wrong?

**Comment by jamierumbelow** [comment]
That's not your fault - that's a bug! Thanks for bringing it to my attention.

To fix it, insert this - from the book - just before line 46:

```
$view = strtolower(get_class($this)) . '/' . $method;
```

Try your best to follow the book in order to learn what's going on. If you'd like to use a newer version of the `MY_Controller` stuff, you can check out the [updated version of the standalone MY_Controller class](https://github.com/jamierumbelow/codeigniter-base-controller).

**Comment by carlotrimarchi** [comment]
Thank you for the answer. I've found that was missing line and solved it today, but I didn't have the time to reply here. Thanks again.
